server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: header_route
          uri: http://localhost:8080
          predicates:
            - Header=X-Tenant, mbodev
          filters:
            - AddRequestHeader=Authorization, Basic dXNlcm5hbWU6cGFzc3dvcmQ=
      default-filters:
        - name: CircuitBreaker
          args:
            name: fallbackCircuitBreaker
            fallbackUri: forward:/fallback
        - PreserveHostHeader
        - name: RequestSize
          args:
            maxSize: 5MB
        - SecureHeaders
        - DedupeResponseHeader=Vary Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
              - OPTIONS
            allowedHeaders:
              - Accept
              - Content-Type
              - Origin
              - X-Tenant
            allowCredentials: false
        add-to-simple-url-handler-mapping: true
